### ISSUE TITLE
Hi what is this

### ISSUE THREAD

**Issue by xavierlyu** [Asap7772/TrailBlazer#1]
This maze stuff looks cool but
What is going on?
Who is asap7772?
Why am I subscribed?

**Comment by Asap7772** [comment]
Sorry Xavier,

This is me, Anikait, and this is my solution to the project aravind gave me.

Thanks.
-Anikait Singh

On Tue, Jan 26, 2016 at 9:32 PM, xavierlu notifications@github.com wrote:

> This maze stuff looks cool but
> What is going on?
> Who is asap7772?
> Why am I subscribed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Asap7772/TrailBlazer/issues/1.

## 

Anikait Singh

**Comment by xavierlyu** [comment]
Lol ur code looks nice. That's just a practice. Come to the pretest tomorrow and hopefully u will pass

**Comment by Asap7772** [comment]
Thanks

On Tue, Jan 26, 2016 at 9:48 PM, xavierlu notifications@github.com wrote:

> Lol ur code looks nice. That's just a practice. Come to the pretest
> tomorrow and hopefully u will pass
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Asap7772/TrailBlazer/issues/1#issuecomment-175356969.

## 

Anikait Singh

**Comment by Asap7772** [comment]
Is there programming today?

On Tue, Jan 26, 2016 at 9:50 PM, Anikait Singh singh.anikait@gmail.com
wrote:

> Thanks
> 
> On Tue, Jan 26, 2016 at 9:48 PM, xavierlu notifications@github.com
> wrote:
> 
> > Lol ur code looks nice. That's just a practice. Come to the pretest
> > tomorrow and hopefully u will pass
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Asap7772/TrailBlazer/issues/1#issuecomment-175356969
> > .
> 
> ## 
> 
> Anikait Singh

## 

Anikait Singh
